# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0002_auto_20170211_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstocare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='cancer',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='cd4history',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='ceaenrollmentchecklist',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='circumcised',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='circumcision',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='clinicquestionnaire',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='communityengagement',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='elisahivresult',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='heartattack',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hicenrollment',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalaccesstocare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalcancer',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalcd4history',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalceaenrollmentchecklist',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalcircumcised',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalcircumcision',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalclinicquestionnaire',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunityengagement',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicaldemographics',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicaleducation',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalelisahivresult',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalgrant',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalheartattack',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhicenrollment',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivcareadherence',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivhealthcarecosts',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivlinkagetocare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivmedicalcare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivrelatedillness',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivresult',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivresultdocumentation',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivtested',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivtestinghistory',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivtestreview',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhivuntested',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhospitaladmission',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalhouseholdcomposition',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicallabourmarketwages',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalmedicaldiagnoses',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalnonpregnancy',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicaloutpatientcare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalparticipation',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalpimacd4',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalpimavl',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalpositiveparticipant',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalpregnancy',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalqualityoflife',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalrecentpartner',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalreproductivehealth',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalresidencymobility',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalresourceutilization',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalrespondent',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalsecondpartner',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalsexualbehaviour',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalstigma',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalstigmaopinion',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectreferral',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalsubstanceuse',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicaltbsymptoms',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalthirdpartner',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicaltuberculosis',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicaluncircumcised',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='historicalviralloadresult',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivcareadherence',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivhealthcarecosts',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivlinkagetocare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivmedicalcare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivrelatedillness',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivresult',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivresultdocumentation',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivtested',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivtestinghistory',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivtestreview',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hivuntested',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hospitaladmission',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='householdcomposition',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='hypertensioncardiovascular',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='immigrationstatus',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='labourmarketwages',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='medicaldiagnoses',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='nonpregnancy',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='outpatientcare',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='pimacd4',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='pimavl',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='positiveparticipant',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='qualityoflife',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='recentpartner',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='reproductivehealth',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='residencymobility',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='resourceutilization',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='secondpartner',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='sexualbehaviour',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='stigma',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='stigmaopinion',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='subjectreferral',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='substanceuse',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='tbsymptoms',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='thirdpartner',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='tuberculosis',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='uncircumcised',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AddField(
            model_name='viralloadresult',
            name='form_as_json',
            field=models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='new', help_text="If the visit has already begun, only 'in progress' or 'incomplete' are valid options", max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='appt_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='new', help_text="If the visit has already begun, only 'in progress' or 'incomplete' are valid options", max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalresidencymobility',
            name='permanent_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If participant has moved into the community in the past 12 months, then since moving in has the participant typically spent more than 14 nights per month in this community.', max_length=10, verbose_name='In the past 12 months, have you typically spent 14 or more nights per month in this community? '),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='bm_refused_reason',
            field=models.CharField(choices=[('afraid', 'I am afraid to know my blood pressure'), ('no_time', 'I do not have time'), ('painful', 'I was told it is painful'), ('not_ready', 'I am not ready'), ('not_sure', 'I am not sure why'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, verbose_name='If no, provide reason'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='bp_refused_reason',
            field=models.CharField(choices=[('afraid', 'I am afraid to know my blood pressure'), ('no_time', 'I do not have time'), ('painful', 'I was told it is painful'), ('not_ready', 'I am not ready'), ('not_sure', 'I am not sure why'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, verbose_name='If no, provide reason'),
        ),
        migrations.AlterField(
            model_name='residencymobility',
            name='permanent_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If participant has moved into the community in the past 12 months, then since moving in has the participant typically spent more than 14 nights per month in this community.', max_length=10, verbose_name='In the past 12 months, have you typically spent 14 or more nights per month in this community? '),
        ),
    ]
