# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0003_auto_20170213_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhivtestinghistory',
            name='has_tested_since',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Have tested for HIV since we last saw you on {previous}?'),
        ),
        migrations.AddField(
            model_name='hivtestinghistory',
            name='has_tested_since',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Have tested for HIV since we last saw you on {previous}?'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='ethnic',
            field=models.CharField(choices=[('Babirwa', 'Babirwa'), ('Bahambukushu', 'Bahambukushu'), ('Baherero', 'Baherero'), ('Bahurutshe', 'Bahurutshe'), ('Bakalaka', 'Bakalaka'), ('Bakgatla', 'Bakgatla'), ('Bakwena', 'Bakwena'), ('Balete', 'Balete'), ('Bangwaketse', 'Bangwaketse'), ('Bangwato', 'Bangwato'), ('Bakgalagadi', 'Bakgalagadi'), ('Bakhurutse', 'Bakhurutse'), ('Barolong', 'Barolong'), ('Basarwa', 'Basarwa'), ('Basobea', 'Basobea'), ('Batalaote', 'Batalaote'), ('Batawana', 'Batawana'), ('Batlokwa', 'Batlokwa'), ('Batswapong', 'Batswapong'), ('Bayei', 'Bayei'), ('Bazezuri/Shona', 'Bazezuri'), ('Indian African', 'Indian African'), ('Asian', 'Asian'), ('White African', 'White African'), ('OTHER', 'Other, specify'), ('DWTA', "Don't want to answer")], help_text='Ask for the original ethnic group', max_length=25, verbose_name='What is your ethnic group?'),
        ),
        migrations.AlterField(
            model_name='education',
            name='job_description',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer (own land)'), ('farm work', 'Farm work on employers land'), ('domestic', 'Domestic worker'), ('bar/hotel', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('fishing', 'Fishing'), ('mining', 'Mining'), ('tourism', 'Tourism/game parks'), ('shop', 'Working in shop / small business'), ('selling', 'Informal selling'), ('sexworker', 'Commercial sex work'), ('transport', 'Transport (trucker/ taxi driver)'), ('factory', 'Factory worker'), ('guard', 'Guard (security company)'), ('police', 'Police/ Soldier'), ('office', 'Clerical and office work'), ('govt worker', 'Government worker'), ('teacher', 'Teacher'), ('hcw', 'Health care worker'), ('other_professional', 'Other professional'), ('OTHER', 'Other')], max_length=65, null=True, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing.'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='ethnic',
            field=models.CharField(choices=[('Babirwa', 'Babirwa'), ('Bahambukushu', 'Bahambukushu'), ('Baherero', 'Baherero'), ('Bahurutshe', 'Bahurutshe'), ('Bakalaka', 'Bakalaka'), ('Bakgatla', 'Bakgatla'), ('Bakwena', 'Bakwena'), ('Balete', 'Balete'), ('Bangwaketse', 'Bangwaketse'), ('Bangwato', 'Bangwato'), ('Bakgalagadi', 'Bakgalagadi'), ('Bakhurutse', 'Bakhurutse'), ('Barolong', 'Barolong'), ('Basarwa', 'Basarwa'), ('Basobea', 'Basobea'), ('Batalaote', 'Batalaote'), ('Batawana', 'Batawana'), ('Batlokwa', 'Batlokwa'), ('Batswapong', 'Batswapong'), ('Bayei', 'Bayei'), ('Bazezuri/Shona', 'Bazezuri'), ('Indian African', 'Indian African'), ('Asian', 'Asian'), ('White African', 'White African'), ('OTHER', 'Other, specify'), ('DWTA', "Don't want to answer")], help_text='Ask for the original ethnic group', max_length=25, verbose_name='What is your ethnic group?'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='job_description',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer (own land)'), ('farm work', 'Farm work on employers land'), ('domestic', 'Domestic worker'), ('bar/hotel', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('fishing', 'Fishing'), ('mining', 'Mining'), ('tourism', 'Tourism/game parks'), ('shop', 'Working in shop / small business'), ('selling', 'Informal selling'), ('sexworker', 'Commercial sex work'), ('transport', 'Transport (trucker/ taxi driver)'), ('factory', 'Factory worker'), ('guard', 'Guard (security company)'), ('police', 'Police/ Soldier'), ('office', 'Clerical and office work'), ('govt worker', 'Government worker'), ('teacher', 'Teacher'), ('hcw', 'Health care worker'), ('other_professional', 'Other professional'), ('OTHER', 'Other')], max_length=65, null=True, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing.'),
        ),
        migrations.AlterField(
            model_name='historicalhivtestinghistory',
            name='when_hiv_test',
            field=models.CharField(blank=True, choices=[('In the last month', 'In the last month'), ('1 to 5 months ago', '1 to 5 months ago'), ('6 to 12 months ago', '6 to 12 months ago'), ('more than 12 months ago', 'more than 12 months ago'), ('not_sure', 'I am not sure'), ('DWTA', "Don't want to answer")], help_text='(verbal response)', max_length=25, null=True, verbose_name='When was the last, most recent, time you were tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='hivtestinghistory',
            name='when_hiv_test',
            field=models.CharField(blank=True, choices=[('In the last month', 'In the last month'), ('1 to 5 months ago', '1 to 5 months ago'), ('6 to 12 months ago', '6 to 12 months ago'), ('more than 12 months ago', 'more than 12 months ago'), ('not_sure', 'I am not sure'), ('DWTA', "Don't want to answer")], help_text='(verbal response)', max_length=25, null=True, verbose_name='When was the last, most recent, time you were tested for HIV?'),
        ),
    ]
