# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0004_auto_20170213_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhivtestinghistory',
            name='has_tested_since',
        ),
        migrations.RemoveField(
            model_name='hivtestinghistory',
            name='has_tested_since',
        ),
    ]
