# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0005_auto_20170213_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhivtested',
            name='arvs_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=25, null=True, verbose_name='Do you believe that treatment for HIV with antiretroviral therapy (or ARVs) can help HIV-positive people to live longer?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='hiv_pills',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=25, null=True, verbose_name='Have you ever heard about treatment for HIV with pills called antiretroviral therapy or ARVs [or HAART]?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='num_hiv_tests',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many times before today have you had an HIV test?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='where_hiv_test',
            field=models.CharField(choices=[('Tebelopele VCT center', 'Tebelopele VCT center'), ('Antenatal care at healthcare facility', 'Antenatal care at healthcare facility (including private clinics)'), ('Other (not antenatal care) at healthcare facility', 'Other (not antenatal care) at healthcare facility (including private clinics)'), ('In my house as part of door-to-door services', 'In my house as part of door-to-door services'), ('In a mobile tent or vehicle in my neighborhood', 'In a mobile tent or vehicle in my neighborhood'), ('Ya_Tsie HIV Test Campaign', 'Ya Tsie HIV Test Campaign'), ('OTHER', 'Other, specify:'), ('not_sure', 'I am not sure'), ('DWTA', "Don't want to answer")], max_length=85, verbose_name='Where were you tested for HIV, the last most recent time you were tested?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='why_hiv_test',
            field=models.CharField(choices=[('I was worried I might have HIV and wanted to know my status', 'I was worried I might have HIV and wanted to know my status'), ('I heard from someone I trust that it is important for me to get tested for HIV ', 'I heard from someone I trust that it is important for me to get tested for HIV '), ('I was at a health facility where the doctor/nurse recommended I get tested for HIV during the same visit', 'I was at a health facility where the doctor/nurse recommended I get tested for HIV during the same visit'), ('I read information on a brochure/flier that it is important for me to get tested for HIV', 'I read information on a brochure/flier that it is important for me to get tested for HIV'), ('I had information from the Ya_Tsie study that it was importantto get tested for HIV', 'I had information from the Ya_Tsie studythat it was important to get tested for HIV'), ('OTHER', 'Other'), ('not_sure', 'I am not sure'), ('DWTA', "Don't want to answer")], max_length=105, null=True, verbose_name="Not including today's HIV test, which of the following statements best describes the reason you were tested the last most recent time you were tested before today?"),
        ),
        migrations.AlterField(
            model_name='historicalhivtestinghistory',
            name='has_record',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('record refusal', 'Participant does not want to provide record')], help_text='For example, OPD card, Tebelopele, Ya Tsie, other.', max_length=45, null=True, verbose_name='Is a record of last most recent HIV test available to review?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtestinghistory',
            name='verbal_hiv_result',
            field=models.CharField(blank=True, choices=[('POS', 'HIV Positive'), ('NEG', 'HIV Negative'), ('IND', 'Indeterminate'), ('UNK', 'I am not sure'), ('DWTA', "Don't want to answer")], help_text='(verbal response)', max_length=30, null=True, verbose_name='Please tell me the results of your last most recent HIV test?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='arvs_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=25, null=True, verbose_name='Do you believe that treatment for HIV with antiretroviral therapy (or ARVs) can help HIV-positive people to live longer?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='hiv_pills',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=25, null=True, verbose_name='Have you ever heard about treatment for HIV with pills called antiretroviral therapy or ARVs [or HAART]?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='num_hiv_tests',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many times before today have you had an HIV test?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='where_hiv_test',
            field=models.CharField(choices=[('Tebelopele VCT center', 'Tebelopele VCT center'), ('Antenatal care at healthcare facility', 'Antenatal care at healthcare facility (including private clinics)'), ('Other (not antenatal care) at healthcare facility', 'Other (not antenatal care) at healthcare facility (including private clinics)'), ('In my house as part of door-to-door services', 'In my house as part of door-to-door services'), ('In a mobile tent or vehicle in my neighborhood', 'In a mobile tent or vehicle in my neighborhood'), ('Ya_Tsie HIV Test Campaign', 'Ya Tsie HIV Test Campaign'), ('OTHER', 'Other, specify:'), ('not_sure', 'I am not sure'), ('DWTA', "Don't want to answer")], max_length=85, verbose_name='Where were you tested for HIV, the last most recent time you were tested?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='why_hiv_test',
            field=models.CharField(choices=[('I was worried I might have HIV and wanted to know my status', 'I was worried I might have HIV and wanted to know my status'), ('I heard from someone I trust that it is important for me to get tested for HIV ', 'I heard from someone I trust that it is important for me to get tested for HIV '), ('I was at a health facility where the doctor/nurse recommended I get tested for HIV during the same visit', 'I was at a health facility where the doctor/nurse recommended I get tested for HIV during the same visit'), ('I read information on a brochure/flier that it is important for me to get tested for HIV', 'I read information on a brochure/flier that it is important for me to get tested for HIV'), ('I had information from the Ya_Tsie study that it was importantto get tested for HIV', 'I had information from the Ya_Tsie studythat it was important to get tested for HIV'), ('OTHER', 'Other'), ('not_sure', 'I am not sure'), ('DWTA', "Don't want to answer")], max_length=105, null=True, verbose_name="Not including today's HIV test, which of the following statements best describes the reason you were tested the last most recent time you were tested before today?"),
        ),
        migrations.AlterField(
            model_name='hivtestinghistory',
            name='has_record',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('record refusal', 'Participant does not want to provide record')], help_text='For example, OPD card, Tebelopele, Ya Tsie, other.', max_length=45, null=True, verbose_name='Is a record of last most recent HIV test available to review?'),
        ),
        migrations.AlterField(
            model_name='hivtestinghistory',
            name='verbal_hiv_result',
            field=models.CharField(blank=True, choices=[('POS', 'HIV Positive'), ('NEG', 'HIV Negative'), ('IND', 'Indeterminate'), ('UNK', 'I am not sure'), ('DWTA', "Don't want to answer")], help_text='(verbal response)', max_length=30, null=True, verbose_name='Please tell me the results of your last most recent HIV test?'),
        ),
    ]
