# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0007_auto_20170214_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreproductivehealth',
            name='given_birth',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Have you given birth since we last spoke with you on {previous}'),
        ),
        migrations.AddField(
            model_name='historicalreproductivehealth',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=3, null=True, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AddField(
            model_name='reproductivehealth',
            name='given_birth',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Have you given birth since we last spoke with you on {previous}'),
        ),
        migrations.AddField(
            model_name='reproductivehealth',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=3, null=True, verbose_name='Do you wish to have a child now or in the future?'),
        ),
    ]
