# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0008_auto_20170214_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='ethnic',
            field=models.CharField(choices=[('Babirwa', 'Babirwa'), ('Bahambukushu', 'Bahambukushu'), ('Baherero', 'Baherero'), ('Bahurutshe', 'Bahurutshe'), ('Bakalaka', 'Bakalaka'), ('Bakgatla', 'Bakgatla'), ('Bakwena', 'Bakwena'), ('Balete', 'Balete'), ('Bangwaketse', 'Bangwaketse'), ('Bangwato', 'Bangwato'), ('Bakgalagadi', 'Bakgalagadi'), ('Bakhurutse', 'Bakhurutse'), ('Barolong', 'Barolong'), ('Basarwa', 'Basarwa'), ('Basobea', 'Basobea'), ('Batalaote', 'Batalaote'), ('Batawana', 'Batawana'), ('Batlokwa', 'Batlokwa'), ('Batswapong', 'Batswapong'), ('Bayei', 'Bayei'), ('Bazezuri/Shona', 'Bazezuri'), ('Indian African', 'Indian African'), ('Asian', 'Asian'), ('White African', 'White African'), ('OTHER', 'Other, specify'), ('DWTA', "Don't want to answer")], help_text='Ask for the original ethnic group', max_length=25, null=True, verbose_name='What is your ethnic group?'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='religion',
            field=models.CharField(choices=[('anglican', 'Anglican'), ('apostolic', 'Apostolic'), ('baptist', 'Baptist'), ('catholic', 'Catholic'), ('evangelical', 'Evangelical'), ('methodist', 'Methodist'), ('pentecostal', 'Pentecostal'), ('traditionalist', 'Traditionalist'), ('zcc', 'ZCC'), ('muslim', 'Islam'), ('hindu', 'Hinduism'), ('buddhist', 'Buddhism'), ('OTHER', 'Other, specify'), ('No affiliation', 'No affiliation')], max_length=25, null=True, verbose_name='What is your religious affiliation?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='ethnic',
            field=models.CharField(choices=[('Babirwa', 'Babirwa'), ('Bahambukushu', 'Bahambukushu'), ('Baherero', 'Baherero'), ('Bahurutshe', 'Bahurutshe'), ('Bakalaka', 'Bakalaka'), ('Bakgatla', 'Bakgatla'), ('Bakwena', 'Bakwena'), ('Balete', 'Balete'), ('Bangwaketse', 'Bangwaketse'), ('Bangwato', 'Bangwato'), ('Bakgalagadi', 'Bakgalagadi'), ('Bakhurutse', 'Bakhurutse'), ('Barolong', 'Barolong'), ('Basarwa', 'Basarwa'), ('Basobea', 'Basobea'), ('Batalaote', 'Batalaote'), ('Batawana', 'Batawana'), ('Batlokwa', 'Batlokwa'), ('Batswapong', 'Batswapong'), ('Bayei', 'Bayei'), ('Bazezuri/Shona', 'Bazezuri'), ('Indian African', 'Indian African'), ('Asian', 'Asian'), ('White African', 'White African'), ('OTHER', 'Other, specify'), ('DWTA', "Don't want to answer")], help_text='Ask for the original ethnic group', max_length=25, null=True, verbose_name='What is your ethnic group?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='religion',
            field=models.CharField(choices=[('anglican', 'Anglican'), ('apostolic', 'Apostolic'), ('baptist', 'Baptist'), ('catholic', 'Catholic'), ('evangelical', 'Evangelical'), ('methodist', 'Methodist'), ('pentecostal', 'Pentecostal'), ('traditionalist', 'Traditionalist'), ('zcc', 'ZCC'), ('muslim', 'Islam'), ('hindu', 'Hinduism'), ('buddhist', 'Buddhism'), ('OTHER', 'Other, specify'), ('No affiliation', 'No affiliation')], max_length=25, null=True, verbose_name='What is your religious affiliation?'),
        ),
        migrations.AlterField(
            model_name='historicalreproductivehealth',
            name='given_birth',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Have you given birth in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreferral',
            name='referral_code',
            field=models.CharField(choices=[('pending', '<data collection in progress>'), ('TST-CD4', 'POS any, need CD4 testing'), ('TST-HIV', 'HIV test'), ('TST-IND', 'Indeterminate result'), ('MASA-CC', 'Known POS, MASA continued care'), ('MASA-DF', 'Known POS, MASA defaulter (was on ART)'), ('SMC-NEG', 'SMC (uncircumcised, hiv neg)'), ('SMC?NEG', 'SMC (Unknown circumcision status, hiv neg'), ('SMC-UNK', 'SMC (uncircumcised, hiv result not known)'), ('NEG!-PR', 'NEG today, Pregnant'), ('POS!-PR', 'POS today, Pregnant'), ('UNK?-PR', 'HIV UNKNOWN, Pregnant'), ('POS#-AN', 'Known POS, Pregnant, on ART (ANC)'), ('POS#-PR', 'Known POS, Pregnant, not on ART'), ('POS!-HI', 'POS today, not on ART, high CD4)'), ('POS!-LO', 'POS today, not on ART, low CD4)'), ('POS#-HI', 'Known POS, not on ART, high CD4)'), ('POS#-LO', 'Known POS, not on ART, low CD4)')], default='pending', editable=False, help_text='list of referral codes confirmed by the edc, comma delimited if more than one (derived).', max_length=50, verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='alcohol_counselling',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Have you ever been counselled about correct alcohol intake by a healthcare worker in the past 3 years?'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='blood_test_for_cholesterol',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Have you ever had a blood test for high cholesterol in the past 3 years?'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='blood_test_for_diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Have you ever had blood test for sugar diabetes in the past 3 years?'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='medication_given',
            field=models.ManyToManyField(blank=True, related_name='medication_given', to='bcpp_subject.Medication', verbose_name='If yes: Are you still being given this medication (respond for each one ticked)'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='medication_taken',
            field=models.ManyToManyField(blank=True, related_name='medication_taken', to='bcpp_subject.Medication', verbose_name='Have you ever taken any of these medications? Tick all that apply'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='physical_activity_counselling',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Have you ever been counselled about the amount of physical activity (or exercise) to maintain by a healthcare worker in the past 3 years?'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='weight_counselling',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Have you ever been counselled about what weight you should aim for by a health care worker in the past 3 years? '),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='weight_history',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Have you had your weight checked in the past 3 years?'),
        ),
        migrations.AlterField(
            model_name='reproductivehealth',
            name='given_birth',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Have you given birth in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='subjectreferral',
            name='referral_code',
            field=models.CharField(choices=[('pending', '<data collection in progress>'), ('TST-CD4', 'POS any, need CD4 testing'), ('TST-HIV', 'HIV test'), ('TST-IND', 'Indeterminate result'), ('MASA-CC', 'Known POS, MASA continued care'), ('MASA-DF', 'Known POS, MASA defaulter (was on ART)'), ('SMC-NEG', 'SMC (uncircumcised, hiv neg)'), ('SMC?NEG', 'SMC (Unknown circumcision status, hiv neg'), ('SMC-UNK', 'SMC (uncircumcised, hiv result not known)'), ('NEG!-PR', 'NEG today, Pregnant'), ('POS!-PR', 'POS today, Pregnant'), ('UNK?-PR', 'HIV UNKNOWN, Pregnant'), ('POS#-AN', 'Known POS, Pregnant, on ART (ANC)'), ('POS#-PR', 'Known POS, Pregnant, not on ART'), ('POS!-HI', 'POS today, not on ART, high CD4)'), ('POS!-LO', 'POS today, not on ART, low CD4)'), ('POS#-HI', 'Known POS, not on ART, high CD4)'), ('POS#-LO', 'Known POS, not on ART, low CD4)')], default='pending', editable=False, help_text='list of referral codes confirmed by the edc, comma delimited if more than one (derived).', max_length=50, verbose_name='Referral Code'),
        ),
    ]
