# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 16:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0009_auto_20170214_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhivhealthcarecosts',
            name='care_regularity',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('0 times', '0 times'), ('1 time', '1 time'), ('2 times', '2 times'), ('3 times', '3 times'), ('4 times', '4 times'), ('5 times', '5 times'), ('6-10 times', '6-10 times'), ('More than 10 times', 'More than 10 times'), ('DWTA', "Don't want to answer")], default='N/A', help_text='Do not include medicine re-fill visits.', max_length=20, verbose_name='In the past 3 months, how many times did you have clinic visits to see a health care worker, a nurse, or doctor? '),
        ),
        migrations.AlterField(
            model_name='historicalhivhealthcarecosts',
            name='doctor_visits',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('always', 'All of the time (always)'), ('almost always', 'Most of the time (almost always)'), ('sometimes', 'Some of the time (sometimes)'), ('rarely', 'Almost none of the time (rarely)'), ('never', 'None of the time (never)'), ('DWTA', "Don't want to answer")], default='N/A', max_length=32, verbose_name='In the last 3 months, how often did someone take you to the doctor?'),
        ),
        migrations.AlterField(
            model_name='historicalhivhealthcarecosts',
            name='place_care_received',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('Government dispensary', 'Government dispensary'), ('Government health center', 'Government health center'), ('Government hospital', 'Government hospital'), ('Christian/mission health center', 'Christian/mission health center'), ('Islamic health center', 'Islamic health center'), ('Private health center for all illnesses', 'Private health center for all illnesses'), ('Private health center for HIV/AIDS', 'Private health center for HIV/AIDS'), ('Mobile services', 'Mobile services'), ('Plantation health center', 'Plantation health center'), ('NGO clinic', 'NGO clinic'), ('DWTA', "Don't want to answer")], default='N/A', max_length=40, verbose_name='Where do you receive most of your HIV related health care? '),
        ),
        migrations.AlterField(
            model_name='historicalhivhealthcarecosts',
            name='reason_no_care',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('not thinking about HIV care', 'I am not thinking about HIV related medical/clinical care at this time'), ('I am not ready to start', 'HIV related medical/clinical care for my HIV infection is important to me but I am not ready to start it yet'), ('not yet tried to find a doctor', 'I have thought about starting HIV related medical/clinical care but have not yet tried to find a doctor or clinic'), ('not yet tried to make an appointment', 'I have found a doctor or clinic for HIV related medical/clinical care but have not yet tried to make an appointment'), ('no been successful yet', 'I have tried to obtain HIV related medical/clinical care from a doctor or clinic but have not been successful yet'), ('I have an appointment for HIV care', 'I have an appointment for HIV related medical/clinical care for my HIV infection but have not been for it yet'), ("don't know where to go", "I don't know where to go for HIV related medical/clinical care"), ('I do not have the money', 'I do not have the money for HIV related medical/clinical care'), ('DWTA', "Don't want to answer")], default='N/A', max_length=115, verbose_name='If you have never received HIV related medical/clinical care, why not? '),
        ),
        migrations.AlterField(
            model_name='historicaloutpatientcare',
            name='outpatient_expense',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If participant has not paid anything for outpatient medical care, please enter 0.00', max_digits=10, null=True, verbose_name='For this most recent outpatient medical care visit, how much did you have to pay, in PULA, to the health care provider, including any medicines?'),
        ),
        migrations.AlterField(
            model_name='hivhealthcarecosts',
            name='care_regularity',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('0 times', '0 times'), ('1 time', '1 time'), ('2 times', '2 times'), ('3 times', '3 times'), ('4 times', '4 times'), ('5 times', '5 times'), ('6-10 times', '6-10 times'), ('More than 10 times', 'More than 10 times'), ('DWTA', "Don't want to answer")], default='N/A', help_text='Do not include medicine re-fill visits.', max_length=20, verbose_name='In the past 3 months, how many times did you have clinic visits to see a health care worker, a nurse, or doctor? '),
        ),
        migrations.AlterField(
            model_name='hivhealthcarecosts',
            name='doctor_visits',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('always', 'All of the time (always)'), ('almost always', 'Most of the time (almost always)'), ('sometimes', 'Some of the time (sometimes)'), ('rarely', 'Almost none of the time (rarely)'), ('never', 'None of the time (never)'), ('DWTA', "Don't want to answer")], default='N/A', max_length=32, verbose_name='In the last 3 months, how often did someone take you to the doctor?'),
        ),
        migrations.AlterField(
            model_name='hivhealthcarecosts',
            name='place_care_received',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('Government dispensary', 'Government dispensary'), ('Government health center', 'Government health center'), ('Government hospital', 'Government hospital'), ('Christian/mission health center', 'Christian/mission health center'), ('Islamic health center', 'Islamic health center'), ('Private health center for all illnesses', 'Private health center for all illnesses'), ('Private health center for HIV/AIDS', 'Private health center for HIV/AIDS'), ('Mobile services', 'Mobile services'), ('Plantation health center', 'Plantation health center'), ('NGO clinic', 'NGO clinic'), ('DWTA', "Don't want to answer")], default='N/A', max_length=40, verbose_name='Where do you receive most of your HIV related health care? '),
        ),
        migrations.AlterField(
            model_name='hivhealthcarecosts',
            name='reason_no_care',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('not thinking about HIV care', 'I am not thinking about HIV related medical/clinical care at this time'), ('I am not ready to start', 'HIV related medical/clinical care for my HIV infection is important to me but I am not ready to start it yet'), ('not yet tried to find a doctor', 'I have thought about starting HIV related medical/clinical care but have not yet tried to find a doctor or clinic'), ('not yet tried to make an appointment', 'I have found a doctor or clinic for HIV related medical/clinical care but have not yet tried to make an appointment'), ('no been successful yet', 'I have tried to obtain HIV related medical/clinical care from a doctor or clinic but have not been successful yet'), ('I have an appointment for HIV care', 'I have an appointment for HIV related medical/clinical care for my HIV infection but have not been for it yet'), ("don't know where to go", "I don't know where to go for HIV related medical/clinical care"), ('I do not have the money', 'I do not have the money for HIV related medical/clinical care'), ('DWTA', "Don't want to answer")], default='N/A', max_length=115, verbose_name='If you have never received HIV related medical/clinical care, why not? '),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='bm_refused_reason',
            field=models.CharField(choices=[('afraid', 'I am afraid to know my hips measurements'), ('no_time', 'I do not have time'), ('painful', 'I was told it is painful'), ('not_ready', 'I am not ready'), ('not_sure', 'I am not sure why'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, verbose_name='If no, provide reason'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='hip_reading_one',
            field=models.CharField(blank=True, help_text='in centimeters (cm)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d*[.]?\\d*$', message='Enter a valid number or decimal')], verbose_name='Hip circumference Measurement today (Reading 1)'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='hip_reading_two',
            field=models.CharField(blank=True, help_text='in centimeters (cm)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d*[.]?\\d*$', message='Enter a valid number or decimal')], verbose_name='Hip circumference Measurement today (Reading 2)'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='left_arm_one',
            field=models.CharField(blank=True, help_text='in mmHg. format SYS/DIA, e.g. 120/80', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\/\\d{1,3}$', message='Enter a valid BP in SYS/DIA format')], verbose_name='Left Arm BP 1:'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='left_arm_two',
            field=models.CharField(blank=True, help_text='in mmHg. format SYS/DIA, e.g. 120/80', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\/\\d{1,3}$', message='Enter a valid BP in SYS/DIA format')], verbose_name='Left Arm BP 2:'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='right_arm_one',
            field=models.CharField(blank=True, help_text='in mmHg. format SYS/DIA, e.g. 120/80', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\/\\d{1,3}$', message='Enter a valid BP in SYS/DIA format')], verbose_name='Right Arm BP 1:'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='right_arm_two',
            field=models.CharField(blank=True, help_text='in mmHg. format SYS/DIA, e.g. 120/80', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\/\\d{1,3}$', message='Enter a valid BP in SYS/DIA format')], verbose_name='Right Arm BP 2:'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='waist_reading_one',
            field=models.CharField(blank=True, help_text='in centimeters (cm)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d*[.]?\\d*$', message='Enter a valid number or decimal')], verbose_name='Waist circumference Measurement today (Reading 1)'),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='waist_reading_two',
            field=models.CharField(blank=True, help_text='in centimeters (cm)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d*[.]?\\d*$', message='Enter a valid number or decimal')], verbose_name='Waist circumference Measurement today (Reading 2)'),
        ),
        migrations.AlterField(
            model_name='outpatientcare',
            name='outpatient_expense',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If participant has not paid anything for outpatient medical care, please enter 0.00', max_digits=10, null=True, verbose_name='For this most recent outpatient medical care visit, how much did you have to pay, in PULA, to the health care provider, including any medicines?'),
        ),
    ]
