# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0010_auto_20170214_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='evidence_not_refered',
            new_name='evidence_art',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='evidence_not_refered_other',
            new_name='evidence_art_other',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='evidence_type_clinic',
            new_name='evidence_referral',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='evidence_type_clinic_other',
            new_name='evidence_referral_other',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='clinic_first_datetime',
            new_name='first_attempt_date',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='startered_therapy',
            new_name='initiated',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='reason_recommended_other',
            new_name='initiated_clinic_other',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='startered_therapy_date',
            new_name='initiated_date',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='reason_recommended',
            new_name='reason_recommended_art',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='start_therapy_clininc_other',
            new_name='reason_recommended_art_other',
        ),
        migrations.RenameField(
            model_name='historicalhivlinkagetocare',
            old_name='recommended_therapy',
            new_name='recommended_art',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='evidence_not_refered',
            new_name='evidence_art',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='evidence_not_refered_other',
            new_name='evidence_art_other',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='evidence_type_clinic',
            new_name='evidence_referral',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='evidence_type_clinic_other',
            new_name='evidence_referral_other',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='clinic_first_datetime',
            new_name='first_attempt_date',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='startered_therapy',
            new_name='initiated',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='reason_recommended_other',
            new_name='initiated_clinic_other',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='startered_therapy_date',
            new_name='initiated_date',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='reason_recommended',
            new_name='reason_recommended_art',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='start_therapy_clininc_other',
            new_name='reason_recommended_art_other',
        ),
        migrations.RenameField(
            model_name='hivlinkagetocare',
            old_name='recommended_therapy',
            new_name='recommended_art',
        ),
        migrations.RemoveField(
            model_name='historicalhivlinkagetocare',
            name='diff_clininc',
        ),
        migrations.RemoveField(
            model_name='historicalhivlinkagetocare',
            name='left_clininc_datetime',
        ),
        migrations.RemoveField(
            model_name='historicalhivlinkagetocare',
            name='not_refered_clininc',
        ),
        migrations.RemoveField(
            model_name='historicalhivlinkagetocare',
            name='start_therapy_clininc',
        ),
        migrations.RemoveField(
            model_name='hivlinkagetocare',
            name='diff_clininc',
        ),
        migrations.RemoveField(
            model_name='hivlinkagetocare',
            name='left_clininc_datetime',
        ),
        migrations.RemoveField(
            model_name='hivlinkagetocare',
            name='not_refered_clininc',
        ),
        migrations.RemoveField(
            model_name='hivlinkagetocare',
            name='start_therapy_clininc',
        ),
        migrations.AddField(
            model_name='historicalhivlinkagetocare',
            name='different_clinic',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='If went to a different clinic, specify the clinic'),
        ),
        migrations.AddField(
            model_name='historicalhivlinkagetocare',
            name='failed_attempt_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='If you tried to attend an HIV care clinic and left before you saw a healthcare provider, specify the date?'),
        ),
        migrations.AddField(
            model_name='historicalhivlinkagetocare',
            name='initiated_clinic',
            field=models.CharField(default='digawana', help_text='Indicate the name of the clinic', max_length=25, verbose_name='Which clinic facility did you start/restart ART at?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhivlinkagetocare',
            name='initiated_clinic_community',
            field=models.CharField(help_text='Indicate the community name', max_length=50, null=True, verbose_name='[If Clinic is not the referred clinic] In which community is this clinic located'),
        ),
        migrations.AddField(
            model_name='hivlinkagetocare',
            name='different_clinic',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='If went to a different clinic, specify the clinic'),
        ),
        migrations.AddField(
            model_name='hivlinkagetocare',
            name='failed_attempt_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='If you tried to attend an HIV care clinic and left before you saw a healthcare provider, specify the date?'),
        ),
        migrations.AddField(
            model_name='hivlinkagetocare',
            name='initiated_clinic',
            field=models.CharField(default='digawana', help_text='Indicate the name of the clinic', max_length=25, verbose_name='Which clinic facility did you start/restart ART at?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hivlinkagetocare',
            name='initiated_clinic_community',
            field=models.CharField(help_text='Indicate the community name', max_length=50, null=True, verbose_name='[If Clinic is not the referred clinic] In which community is this clinic located'),
        ),
        migrations.AlterField(
            model_name='historicalhivhealthcarecosts',
            name='reason_no_care',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('not thinking about HIV care', 'I am not thinking about HIV related medical/clinical care at this time'), ('I am not ready to start', 'HIV related medical/clinical care for my HIV infection is important to me but I am not ready to start it yet'), ('not yet tried to find a doctor', 'I have thought about starting HIV related medical/clinical care but have not yet tried to find a doctor or clinic'), ('not yet tried to make an appointment', 'I have found a doctor or clinic for HIV related medical/clinical care but have not yet tried to make an appointment'), ('no been successful yet', 'I have tried to obtain HIV related medical/clinical care from a doctor or clinic but have not been successful yet'), ('I have an appointment for HIV care', 'I have an appointment for HIV related medical/clinical care for my HIV infection but have not been for it yet'), ("don't know where to go", "I don't know where to go for HIV related medical/clinical care"), ('I do not have the money', 'I do not have the money for HIV related medical/clinical care'), ('DWTA', "Don't want to answer")], default='N/A', max_length=115, verbose_name='If you have never received HIV related medical/clinical care, why not?'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='kept_appt',
            field=models.CharField(choices=[('Yes', 'Yes, kept appointment'), ('attended_other_date', 'No but attended a visit at the HIV care clinic to which they were referred on another date'), ('attended_different_clinic', 'No but attended a visit at a different HIV clinic'), ('went_different_clinic', 'I went to a different clinic'), ('no_tried_left', 'No but tried to attend an HIV care clinic and left before I saw a healthcare provider'), ('no_not_been', 'I have not been to any HIV care clinic')], max_length=50, null=True, verbose_name='When we last saw you in {previous} we scheduled an appointment for you in an HIV care clinic on {referral_appt_date}. Did you keep that appointment?'),
        ),
        migrations.AlterField(
            model_name='historicaluncircumcised',
            name='future_circ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=25, null=True, verbose_name='Would you ever consider being circumcised in the future?'),
        ),
        migrations.AlterField(
            model_name='hivhealthcarecosts',
            name='reason_no_care',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('not thinking about HIV care', 'I am not thinking about HIV related medical/clinical care at this time'), ('I am not ready to start', 'HIV related medical/clinical care for my HIV infection is important to me but I am not ready to start it yet'), ('not yet tried to find a doctor', 'I have thought about starting HIV related medical/clinical care but have not yet tried to find a doctor or clinic'), ('not yet tried to make an appointment', 'I have found a doctor or clinic for HIV related medical/clinical care but have not yet tried to make an appointment'), ('no been successful yet', 'I have tried to obtain HIV related medical/clinical care from a doctor or clinic but have not been successful yet'), ('I have an appointment for HIV care', 'I have an appointment for HIV related medical/clinical care for my HIV infection but have not been for it yet'), ("don't know where to go", "I don't know where to go for HIV related medical/clinical care"), ('I do not have the money', 'I do not have the money for HIV related medical/clinical care'), ('DWTA', "Don't want to answer")], default='N/A', max_length=115, verbose_name='If you have never received HIV related medical/clinical care, why not?'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='kept_appt',
            field=models.CharField(choices=[('Yes', 'Yes, kept appointment'), ('attended_other_date', 'No but attended a visit at the HIV care clinic to which they were referred on another date'), ('attended_different_clinic', 'No but attended a visit at a different HIV clinic'), ('went_different_clinic', 'I went to a different clinic'), ('no_tried_left', 'No but tried to attend an HIV care clinic and left before I saw a healthcare provider'), ('no_not_been', 'I have not been to any HIV care clinic')], max_length=50, null=True, verbose_name='When we last saw you in {previous} we scheduled an appointment for you in an HIV care clinic on {referral_appt_date}. Did you keep that appointment?'),
        ),
        migrations.AlterField(
            model_name='uncircumcised',
            name='future_circ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=25, null=True, verbose_name='Would you ever consider being circumcised in the future?'),
        ),
    ]
