# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0011_auto_20170215_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhivlinkagetocare',
            name='initiated_clinic_other',
        ),
        migrations.RemoveField(
            model_name='hivlinkagetocare',
            name='initiated_clinic_other',
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='evidence_art',
            field=models.CharField(choices=[('self_report', 'Self-Report Only'), ('opr_card', 'OPD Card'), ('clinic_paperwork', 'Clinic paperwork'), ('OTHER', 'Other ')], max_length=50, null=True, verbose_name='Type of Evidence:'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='evidence_referral',
            field=models.CharField(choices=[('self_report', 'Self-Report Only'), ('opr_card', 'OPD Card'), ('clinic_paperwork', 'Clinic paperwork'), ('OTHER', 'Other ')], max_length=50, null=True, verbose_name='Type of Evidence:'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='kept_appt',
            field=models.CharField(choices=[('Yes', 'Yes, kept appointment'), ('attended_other_date', 'No but attended a visit at the HIV care clinic to which they were referred on another date'), ('attended_different_clinic', 'No but attended a visit at a different HIV clinic'), ('went_different_clinic', 'I went to a different clinic'), ('failed_attempt', 'No but tried to attend an HIV care clinic and left before I saw a healthcare provider'), ('didnt_attend', 'I have not been to any HIV care clinic')], max_length=50, null=True, verbose_name='When we last saw you in {previous} we scheduled an appointment for you in an HIV care clinic on {referral_appt_date}. Did you keep that appointment?'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='reason_recommended_art',
            field=models.CharField(blank=True, choices=[('low_cd4', 'Low CD4'), ('high_viral_load', 'High viral load'), ('pregnancy_breastfeeding', 'Pregnancy or breastfeeding'), ('tuberculosis', 'Tuberculosis'), ('cancer', 'Cancer'), ('OTHER', 'Other, specify'), ('dont_know', 'Do not know')], max_length=50, null=True, verbose_name='If yes, do you know why ARVs were recommended?'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='evidence_art',
            field=models.CharField(choices=[('self_report', 'Self-Report Only'), ('opr_card', 'OPD Card'), ('clinic_paperwork', 'Clinic paperwork'), ('OTHER', 'Other ')], max_length=50, null=True, verbose_name='Type of Evidence:'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='evidence_referral',
            field=models.CharField(choices=[('self_report', 'Self-Report Only'), ('opr_card', 'OPD Card'), ('clinic_paperwork', 'Clinic paperwork'), ('OTHER', 'Other ')], max_length=50, null=True, verbose_name='Type of Evidence:'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='kept_appt',
            field=models.CharField(choices=[('Yes', 'Yes, kept appointment'), ('attended_other_date', 'No but attended a visit at the HIV care clinic to which they were referred on another date'), ('attended_different_clinic', 'No but attended a visit at a different HIV clinic'), ('went_different_clinic', 'I went to a different clinic'), ('failed_attempt', 'No but tried to attend an HIV care clinic and left before I saw a healthcare provider'), ('didnt_attend', 'I have not been to any HIV care clinic')], max_length=50, null=True, verbose_name='When we last saw you in {previous} we scheduled an appointment for you in an HIV care clinic on {referral_appt_date}. Did you keep that appointment?'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='reason_recommended_art',
            field=models.CharField(blank=True, choices=[('low_cd4', 'Low CD4'), ('high_viral_load', 'High viral load'), ('pregnancy_breastfeeding', 'Pregnancy or breastfeeding'), ('tuberculosis', 'Tuberculosis'), ('cancer', 'Cancer'), ('OTHER', 'Other, specify'), ('dont_know', 'Do not know')], max_length=50, null=True, verbose_name='If yes, do you know why ARVs were recommended?'),
        ),
    ]
