# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0014_subjectrequisition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrequisition',
            name='estimated_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If applicable, estimated volume of sample for this test/order. This is the total volume if number of "tubes" above is greater than 1', max_digits=7, null=True, verbose_name='Estimated volume in mL'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='item_count',
            field=models.IntegerField(blank=True, help_text='Number of tubes, samples, cards, etc being sent for this test/order only. Determines number of labels to print', null=True, verbose_name='Number of items'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='item_type',
            field=models.CharField(blank=True, choices=[('tube', 'Tube'), ('swab', 'Swab'), ('dbs', 'DBS Card'), ('other', 'Other')], max_length=25, null=True, verbose_name='Item collection type'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Specimen type'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='study_site',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
