# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0015_auto_20170216_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrequisition',
            name='reason_not_drawn',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('collection_failed', 'Tried, but unable obtaining sample from patient'), ('absent', 'Patient did not attend visit'), ('refused', 'Patient refused'), ('no_supplies', 'No supplies')], default='N/A', max_length=25, verbose_name='If not drawn, please explain'),
        ),
    ]
