# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0016_auto_20170216_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrequisition',
            name='item_type',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('tube', 'Tube'), ('swab', 'Swab'), ('dbs', 'DBS Card'), ('OTHER', 'Other')], default='N/A', max_length=25, verbose_name='Item collection type'),
        ),
    ]
