# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0017_auto_20170216_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrequisition',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='received_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='requisition_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requisition Date'),
        ),
    ]
