# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0018_auto_20170216_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrequisition',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='packed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='processed_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
