# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0022_subjectrequisition_primary_aliquot_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrequisition',
            name='packed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='processed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='received_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='shipped_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
