# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 21:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0024_auto_20170222_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctconsent',
            name='subject_consent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bcpp_subject.SubjectConsent'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='labour_market_wages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bcpp_subject.LabourMarketWages'),
        ),
        migrations.AlterField(
            model_name='historicalhivresult',
            name='insufficient_vol',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text='Note: if capillary blood volume less than 350uL, an additional venous blood draw is required', max_length=15, verbose_name='If capillary, is the volume less than 350uL?'),
        ),
        migrations.AlterField(
            model_name='historicalreproductivehealth',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=10, null=True, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='last_year_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></br>Leave blank if participant does not want to respond.</p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^([1-9][0-9]*)|([0])$', 'Expected a number greater than or equal to zero')], verbose_name='In the past 12 months, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='lifetime_sex_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^([1-9][0-9]*)|([0])$', 'Expected a number greater than or equal to zero')], verbose_name='In your lifetime, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='hivresult',
            name='insufficient_vol',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text='Note: if capillary blood volume less than 350uL, an additional venous blood draw is required', max_length=15, verbose_name='If capillary, is the volume less than 350uL?'),
        ),
        migrations.AlterField(
            model_name='reproductivehealth',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure')], max_length=10, null=True, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='household_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bcpp_subject.HouseholdComposition'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='last_year_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></br>Leave blank if participant does not want to respond.</p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^([1-9][0-9]*)|([0])$', 'Expected a number greater than or equal to zero')], verbose_name='In the past 12 months, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='lifetime_sex_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^([1-9][0-9]*)|([0])$', 'Expected a number greater than or equal to zero')], verbose_name='In your lifetime, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='subject_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bcpp_subject.SubjectVisit'),
        ),
    ]
