# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0027_auto_20170302_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhivcareadherence',
            name='first_positive',
            field=models.DateField(blank=True, help_text='Note: If participant does not want to answer or is unable to estimate date, leave blank.', null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='When was your first positive HIV test result?'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='evidence_art',
            field=models.CharField(blank=True, choices=[('self_report', 'Self-Report Only'), ('opr_card', 'OPD Card'), ('clinic_paperwork', 'Clinic paperwork'), ('OTHER', 'Other ')], max_length=50, null=True, verbose_name='Type of Evidence:'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='initiated_clinic',
            field=models.CharField(blank=True, help_text='Indicate the name of the clinic', max_length=25, null=True, verbose_name='Which clinic facility did you start/restart ART at?'),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='initiated_clinic_community',
            field=models.CharField(blank=True, help_text='Indicate the community name', max_length=50, null=True, verbose_name='In which community is this clinic located'),
        ),
        migrations.AlterField(
            model_name='hivcareadherence',
            name='first_positive',
            field=models.DateField(blank=True, help_text='Note: If participant does not want to answer or is unable to estimate date, leave blank.', null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='When was your first positive HIV test result?'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='evidence_art',
            field=models.CharField(blank=True, choices=[('self_report', 'Self-Report Only'), ('opr_card', 'OPD Card'), ('clinic_paperwork', 'Clinic paperwork'), ('OTHER', 'Other ')], max_length=50, null=True, verbose_name='Type of Evidence:'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='initiated_clinic',
            field=models.CharField(blank=True, help_text='Indicate the name of the clinic', max_length=25, null=True, verbose_name='Which clinic facility did you start/restart ART at?'),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='initiated_clinic_community',
            field=models.CharField(blank=True, help_text='Indicate the community name', max_length=50, null=True, verbose_name='In which community is this clinic located'),
        ),
    ]
