# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0029_auto_20170315_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousconsent',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=edc_base.utils.get_uuid, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalanonymousconsent',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=edc_base.utils.get_uuid, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=edc_base.utils.get_uuid, editable=False),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=edc_base.utils.get_uuid, editable=False),
        ),
    ]
