# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:14
from __future__ import unicode_literals

from django.db import migrations
import django_crypto_fields.fields.encrypted_text_field


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0031_auto_20170316_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='contact_physical_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, null=True, verbose_name='Full physical address '),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='contact_physical_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, null=True, verbose_name='Full physical address '),
        ),
    ]
