# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:29
from __future__ import unicode_literals

from django.db import migrations
import django_crypto_fields.fields.encrypted_text_field


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0032_auto_20170316_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='subject_work_place',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=250, null=True, verbose_name='Name and location of work place'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='subject_work_place',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=250, null=True, verbose_name='Name and location of work place'),
        ),
    ]
