# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0033_auto_20170316_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='date_signed',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='date_signed',
        ),
    ]
