# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0034_auto_20170316_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpimacd4',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalpimavl',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pimacd4',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pimavl',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
