# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0036_auto_20170316_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhivcareadherence',
            name='ever_taken_arv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer")], help_text='For women, do not include treatment that you took during pregnancy to protect your baby from HIV', max_length=25, verbose_name='Have you ever taken any antiretroviral therapy (ARVs) for your HIV infection?'),
        ),
        migrations.AlterField(
            model_name='historicalhivcareadherence',
            name='on_arv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], help_text='If yes, need to answer next two questions.', max_length=25, verbose_name='Are you currently taking antiretroviral therapy (ARVs)?'),
        ),
        migrations.AlterField(
            model_name='historicalresidencymobility',
            name='permanent_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer")], help_text='If participant has moved into the community in the past 12 months, then since moving in has the participant typically spent more than 14 nights per month in this community.', max_length=10, verbose_name='In the past 12 months, have you typically spent 14 or more nights per month in this community? '),
        ),
        migrations.AlterField(
            model_name='hivcareadherence',
            name='ever_taken_arv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer")], help_text='For women, do not include treatment that you took during pregnancy to protect your baby from HIV', max_length=25, verbose_name='Have you ever taken any antiretroviral therapy (ARVs) for your HIV infection?'),
        ),
        migrations.AlterField(
            model_name='hivcareadherence',
            name='on_arv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], help_text='If yes, need to answer next two questions.', max_length=25, verbose_name='Are you currently taking antiretroviral therapy (ARVs)?'),
        ),
        migrations.AlterField(
            model_name='residencymobility',
            name='permanent_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer")], help_text='If participant has moved into the community in the past 12 months, then since moving in has the participant typically spent more than 14 nights per month in this community.', max_length=10, verbose_name='In the past 12 months, have you typically spent 14 or more nights per month in this community? '),
        ),
    ]
