# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0037_auto_20170322_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='job_description',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer (own land)'), ('farm work', 'Farm work on employers land'), ('domestic', 'Domestic worker'), ('bar/hotel', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('fishing', 'Fishing'), ('mining', 'Mining'), ('tourism', 'Tourism/game parks'), ('shop', 'Working in shop / small business'), ('selling', 'Informal selling'), ('sexworker', 'Commercial sex work'), ('transport', 'Transport (trucker/ taxi driver)'), ('factory', 'Factory worker'), ('guard', 'Guard (security company)'), ('police', 'Police/ Soldier'), ('office', 'Clerical and office work'), ('govt worker', 'Government worker'), ('teacher', 'Teacher'), ('hcw', 'Health care worker'), ('other_professional', 'Other professional'), ('DWTA', "Don't want to answer"), ('OTHER', 'Other')], max_length=65, null=True, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing.'),
        ),
        migrations.AlterField(
            model_name='education',
            name='job_type',
            field=models.CharField(blank=True, choices=[('piece job', 'Occassional or Casual employment (piece job)'), ('seasonal', 'Seasonal employment'), ('full-time', 'Formal wage employment (full-time)'), ('part-time', 'Formal wage employment (part-time)'), ('agric', 'Self-employed in agriculture'), ('self full-time', 'Self-employed making money, full time'), ('self part-time', 'Self-employed making money, part time'), ('DWTA', "Don't want to answer"), ('OTHER', 'Other')], max_length=45, null=True, verbose_name='In your main job what type of work do you do?'),
        ),
        migrations.AlterField(
            model_name='education',
            name='reason_unemployed',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting to continue agricultural work'), ('unemployed- looking', 'Unemployed (looking for work)'), ('unemployed- waiting', 'Unemployed (waiting to start new work)'), ('unable to work', 'Unable to work (permanently sick or injured)'), ('student', 'Student/ Apprentice/ Volunteer'), ('housewife', 'Housewife/ Homemaker (not looking for work)'), ('retired', 'Retired'), ('OTHER', 'Other'), ('not looking', 'Not looking for work'), ('DWTA', "Don't want to answer")], max_length=65, null=True, verbose_name='What is the reason why you are not working?'),
        ),
        migrations.AlterField(
            model_name='education',
            name='working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Are you currently working?'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='job_description',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer (own land)'), ('farm work', 'Farm work on employers land'), ('domestic', 'Domestic worker'), ('bar/hotel', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('fishing', 'Fishing'), ('mining', 'Mining'), ('tourism', 'Tourism/game parks'), ('shop', 'Working in shop / small business'), ('selling', 'Informal selling'), ('sexworker', 'Commercial sex work'), ('transport', 'Transport (trucker/ taxi driver)'), ('factory', 'Factory worker'), ('guard', 'Guard (security company)'), ('police', 'Police/ Soldier'), ('office', 'Clerical and office work'), ('govt worker', 'Government worker'), ('teacher', 'Teacher'), ('hcw', 'Health care worker'), ('other_professional', 'Other professional'), ('DWTA', "Don't want to answer"), ('OTHER', 'Other')], max_length=65, null=True, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing.'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='job_type',
            field=models.CharField(blank=True, choices=[('piece job', 'Occassional or Casual employment (piece job)'), ('seasonal', 'Seasonal employment'), ('full-time', 'Formal wage employment (full-time)'), ('part-time', 'Formal wage employment (part-time)'), ('agric', 'Self-employed in agriculture'), ('self full-time', 'Self-employed making money, full time'), ('self part-time', 'Self-employed making money, part time'), ('DWTA', "Don't want to answer"), ('OTHER', 'Other')], max_length=45, null=True, verbose_name='In your main job what type of work do you do?'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='reason_unemployed',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting to continue agricultural work'), ('unemployed- looking', 'Unemployed (looking for work)'), ('unemployed- waiting', 'Unemployed (waiting to start new work)'), ('unable to work', 'Unable to work (permanently sick or injured)'), ('student', 'Student/ Apprentice/ Volunteer'), ('housewife', 'Housewife/ Homemaker (not looking for work)'), ('retired', 'Retired'), ('OTHER', 'Other'), ('not looking', 'Not looking for work'), ('DWTA', "Don't want to answer")], max_length=65, null=True, verbose_name='What is the reason why you are not working?'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Are you currently working?'),
        ),
        migrations.AlterField(
            model_name='historicalresidencymobility',
            name='intend_residency',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Do you intend to move out of the community in the next 12 months?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='alcohol_sex',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('Neither of us', 'Neither of us'), ('My partner', 'My partner'), ('Myself', 'Myself'), ('Both of us', 'Both of us'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='During the last most recent time you had sex, were you or your partner drinking alcohol?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='condom',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, null=True, verbose_name='During the last most recent time you had sex, did you or your partner use a condom?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='more_sex',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, null=True, verbose_name='In the past 12 months, did you have sex with somebody living outside of the community?'),
        ),
        migrations.AlterField(
            model_name='residencymobility',
            name='intend_residency',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Do you intend to move out of the community in the next 12 months?'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='alcohol_sex',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('Neither of us', 'Neither of us'), ('My partner', 'My partner'), ('Myself', 'Myself'), ('Both of us', 'Both of us'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='During the last most recent time you had sex, were you or your partner drinking alcohol?'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='condom',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, null=True, verbose_name='During the last most recent time you had sex, did you or your partner use a condom?'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='more_sex',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, null=True, verbose_name='In the past 12 months, did you have sex with somebody living outside of the community?'),
        ),
    ]
