# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0038_auto_20170326_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='circumcised',
            name='health_benefits_smc',
            field=models.ManyToManyField(blank=True, to='bcpp_subject.CircumcisionBenefits', verbose_name='What do you believe are the health benefits of male circumcision?'),
        ),
        migrations.AlterField(
            model_name='circumcision',
            name='health_benefits_smc',
            field=models.ManyToManyField(blank=True, to='bcpp_subject.CircumcisionBenefits', verbose_name='What do you believe are the health benefits of male circumcision?'),
        ),
        migrations.AlterField(
            model_name='education',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('None', 'No income'), ('1-199 pula', '1-199 pula'), ('200-499 pula', '200-499 pula'), ('500-999 pula', '500-999 pula'), ('1000-4999 pula', '1000-4999 pula'), ('5000-10,000 pula', '5000-10,000 pula'), ('More than 10,000 pula', 'More than 10,000 pula'), ('DWTA', "Don't want to answer")], help_text='Payments may include retirement benefits, child maintenance, food basket, etc', max_length=25, null=True, verbose_name='In the past month, how much money did you earn from work you did or received in payment?'),
        ),
        migrations.AlterField(
            model_name='historicalcircumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('None', 'No income'), ('1-199 pula', '1-199 pula'), ('200-499 pula', '200-499 pula'), ('500-999 pula', '500-999 pula'), ('1000-4999 pula', '1000-4999 pula'), ('5000-10,000 pula', '5000-10,000 pula'), ('More than 10,000 pula', 'More than 10,000 pula'), ('DWTA', "Don't want to answer")], help_text='Payments may include retirement benefits, child maintenance, food basket, etc', max_length=25, null=True, verbose_name='In the past month, how much money did you earn from work you did or received in payment?'),
        ),
        migrations.AlterField(
            model_name='historicalrecentpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='historicalsecondpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='first_sex',
            field=models.IntegerField(blank=True, help_text='Note:leave blank if participant does not want to respond.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name="How old were you when you had sex for the first time? If you can't recall the exact age, please give a best guess."),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='survival_status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Deceased'), ('unknown', 'Unknown')], default='alive', max_length=10, null=True, verbose_name="Participant's survival status"),
        ),
        migrations.AlterField(
            model_name='historicalthirdpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='historicaluncircumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='historicalviralloadresult',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='recentpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='secondpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='first_sex',
            field=models.IntegerField(blank=True, help_text='Note:leave blank if participant does not want to respond.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name="How old were you when you had sex for the first time? If you can't recall the exact age, please give a best guess."),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='survival_status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Deceased'), ('unknown', 'Unknown')], default='alive', max_length=10, null=True, verbose_name="Participant's survival status"),
        ),
        migrations.AlterField(
            model_name='thirdpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='uncircumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not Sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='uncircumcised',
            name='health_benefits_smc',
            field=models.ManyToManyField(blank=True, to='bcpp_subject.CircumcisionBenefits', verbose_name='What do you believe are the health benefits of male circumcision?'),
        ),
        migrations.AlterField(
            model_name='viralloadresult',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Comment'),
        ),
    ]
