# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0039_auto_20170425_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='bm_refused_reason',
            field=models.CharField(choices=[('afraid', 'I am afraid to know my hips measurements'), ('no_time', 'I do not have time'), ('painful', 'I was told it is painful'), ('not_ready', 'I am not ready'), ('pregnancy', 'Not applicable (pregnancy)'), ('not_sure', 'I am not sure why'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=25, verbose_name='If no, provide reason'),
        ),
    ]
