# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 08:30
from __future__ import unicode_literals

import _socket
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.custom_fields
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_subject', '0041_auto_20170705_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeaOpd',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('form_as_json', models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True)),
                ('consent_version', models.CharField(default='?', editable=False, max_length=10)),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_base.model_validators.date.datetime_not_future, edc_protocol.validators.datetime_not_before_study_start], verbose_name='Report Date')),
                ('times_care_sought', models.IntegerField(verbose_name='In the last 3 months, how many times did you seek care at a Government Primary Health Clinic/Post?')),
                ('times_care_obtained', models.IntegerField(verbose_name='Of the times you sought care, how many times were you able toobtain care?')),
                ('tb_care', models.IntegerField(help_text='TB Diagnosis or Treatment', verbose_name='Of the times you sought care, how many times were you seekingcare for TB?')),
                ('hiv_related', models.IntegerField(help_text='Routine HIV-related care(such as ART start, refill,routinemonitoring', verbose_name='Of the times you sought care, how many times were you seekingcare for HIV related?')),
                ('hiv_related_none_tb', models.IntegerField(help_text='Diagnosis or Treatment of HIV-related illness other thanTB(e.g ARV toxicity,illness)', verbose_name='Of the times you sought care, how many times were you seekingcare for HIV-related illness than TB?')),
                ('pregnancy_related', models.IntegerField(help_text='Pregnancy related care (e.g. antenatal, postnatal care', verbose_name='Of the times you sought care, how many times were you seekingcare for Pregnancy related care?')),
                ('injury_accident', models.IntegerField(help_text='Injury or accident', verbose_name='Of the times you sought care, how many times were you seekingcare for Injury or Accident?')),
                ('chronic_disease', models.IntegerField(help_text='Chronic disease-related care(e.g high blood pressure,diabetes, depression', verbose_name='Of the times you sought care, how many times were you seekingcare for Chronic disease care?')),
                ('cancer_care', models.IntegerField(help_text='Cancer diagnosis, treatment', verbose_name='Of the times you sought care, how many times were you seekingcare for Cancer?')),
                ('other_care', edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=15, null=True, verbose_name='...if "Other", specify')),
                ('other_care_count', edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=15, null=True, verbose_name='...if "Other", specify')),
                ('marriage_certificate_no', models.CharField(blank=True, help_text='e.g. 000/YYYY', max_length=9, null=True, verbose_name='What is the marriage certificate number?')),
                ('lab_tests_ordered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If yes, indicate which of the following were ordered ', max_length=3, verbose_name='For the most recent time that you sought care, were any labtests ordered? ')),
                ('tests_ordered', models.CharField(choices=[('Hematology', 'Hematology'), ('Chemistry', 'Chemistry'), ('CD4 count', 'CD4 count'), ('HIV-1 RNA (viral load)', 'HIV-1 RNA (viral load)'), ('Microbiology', 'Microbiology'), ('Radiology', 'Radiology'), ('Pathology', 'Pathology'), ('N/A', 'Not Applicable'), ('OTHER', 'Other (specify)')], max_length=25)),
                ('ordered_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=15, null=True, verbose_name='...if "Other", specify')),
                ('procedures_performed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name=' For the most recent time that you sought care, wereany procedures performed?  ')),
                ('procedure', models.CharField(blank=True, max_length=25, null=True, verbose_name='If yes, describe ')),
                ('medication', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, verbose_name='For the most recent time that you sought care, wereany medications prescribed? ')),
                ('medication_prescribed', models.CharField(choices=[('Antiretroviral medications', 'Antiretroviral medications'), ('Antituberculosis treatment', 'Antituberculosis treatment'), ('Isoniazid preventive therapy', 'Isoniazid preventive therapy'), ('Cotrimoxazole prophylaxis', 'Cotrimoxazole prophylaxis'), ('Antibiotic treatment', 'Antibiotic treatment'), ('Anthihypertensive', 'Anthihypertensive'), ('Diabetes treatment', 'Diabetes treatment'), ('Prenatal vitamin', 'Prenatal vitamin'), ('Paracetamol', 'Paracetamol, profen, or other medicine for treating pain'), ('N/A', 'Not Applicable'), ('OTHER', 'Other (specify)')], max_length=50, verbose_name='If yes, indicate which of the following were prescribed ')),
                ('prescribed_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=15, null=True, verbose_name='...if "Other", specify')),
                ('further_evaluation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='For the most recent time that you sought care, were you referred for further evaluation or treatment?  ')),
                ('evaluation_referred', models.CharField(blank=True, max_length=50, verbose_name='If yes, describe what you were referred for, and towhom you were referred.')),
                ('cd4_date', models.DateField(blank=True, help_text='For HIV-infected participants', null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date of most recent CD4 count')),
                ('cd4_result', models.IntegerField(blank=True, help_text='For HIV-infected participants, in units/mm^3', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Result of most recent CD4 count')),
            ],
            options={
                'verbose_name': 'CEA  OPD Question',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='accesstocare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='anonymousconsent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='arv',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='cd4history',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='ceaenrollmentchecklist',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='circumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='circumcised',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='circumcision',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=15, null=True, verbose_name='Are you circumcised?'),
        ),
        migrations.AlterField(
            model_name='circumcision',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='circumcisionbenefits',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='clinicquestionnaire',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='communityengagement',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='correctconsent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='disenrollmentahs',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='disenrollmentano',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='disenrollmentbhs',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='disenrollmentess',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='education',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='elisahivresult',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='familyplanning',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='grant',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hicenrollment',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalaccesstocare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalanonymousconsent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcancer',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcd4history',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalceaenrollmentchecklist',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcircumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='historicalcircumcised',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcircumcision',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=15, null=True, verbose_name='Are you circumcised?'),
        ),
        migrations.AlterField(
            model_name='historicalcircumcision',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalclinicquestionnaire',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcommunityengagement',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcorrectconsent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalelisahivresult',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalenrollment',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalgrant',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalheartattack',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhicenrollment',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivcareadherence',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivhealthcarecosts',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivlinkagetocare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivmedicalcare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivrelatedillness',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivresult',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivresultdocumentation',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='arvs_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Do you believe that treatment for HIV with antiretroviral therapy (or ARVs) can help HIV-positive people to live longer?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='hiv_pills',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Have you ever heard about treatment for HIV with pills called antiretroviral therapy or ARVs [or HAART]?'),
        ),
        migrations.AlterField(
            model_name='historicalhivtested',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivtestinghistory',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivtestreview',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhivuntested',
            name='arvs_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, verbose_name='Do you believe that treatment for HIV with antiretroviral therapy (or ARVs) can help HIV-positive people to live longer?'),
        ),
        migrations.AlterField(
            model_name='historicalhivuntested',
            name='hiv_pills',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, verbose_name='Have you ever heard about treatment for HIV with pills called antiretroviral therapy or ARVs or HAART?'),
        ),
        migrations.AlterField(
            model_name='historicalhivuntested',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhospitaladmission',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdcomposition',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicallabourmarketwages',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalmedicaldiagnoses',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalnonpregnancy',
            name='hiv_last_pregnancy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], help_text='If respondent was aware that she was HIV-positive prior to last pregnancy', max_length=25, null=True, verbose_name='During your last pregnancy (not current pregnancy) were you tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='historicalnonpregnancy',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalnonpregnancy',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AlterField(
            model_name='historicaloutpatientcare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalparticipation',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalpimacd4',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalpimavl',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalpositiveparticipant',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='hiv_last_pregnancy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], help_text='If respondent was aware that she was HIV-positive prior to last pregnancy', max_length=25, null=True, verbose_name='During your last pregnancy (not current pregnancy) were you tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalqualityoflife',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalrecentpartner',
            name='first_haart',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Is this partner taking antiretroviral treatment?'),
        ),
        migrations.AlterField(
            model_name='historicalrecentpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='historicalrecentpartner',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalrecentpartner',
            name='partner_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Has your partner been tested for HIV in last 12 months'),
        ),
        migrations.AlterField(
            model_name='historicalreproductivehealth',
            name='currently_pregnant',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Are you currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='historicalreproductivehealth',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalreproductivehealth',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=10, null=True, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AlterField(
            model_name='historicalresidencymobility',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalresidencymobility',
            name='intend_residency',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Do you intend to move out of the community in the next 12 months?'),
        ),
        migrations.AlterField(
            model_name='historicalresourceutilization',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalrespondent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsecondpartner',
            name='first_haart',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Is this partner taking antiretroviral treatment?'),
        ),
        migrations.AlterField(
            model_name='historicalsecondpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='historicalsecondpartner',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsecondpartner',
            name='partner_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Has your partner been tested for HIV in last 12 months'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='last_year_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></br>Leave blank if participant does not want to respond.</p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(([1-9])+|[1-9]{1}([0-9])+|0)$', 'Expected a number greater than or equal to zero')], verbose_name='In the past 12 months, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='historicalsexualbehaviour',
            name='lifetime_sex_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(([1-9])+|[1-9]{1}([0-9])+|0)$', 'Expected a number greater than or equal to zero')], verbose_name='In your lifetime, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='historicalstigma',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalstigmaopinion',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='language',
            field=models.CharField(choices=[('tn', 'Setswana'), ('en', 'English'), ('kck', 'Ikalanga'), ('hbs', 'Hambukushu')], help_text='The language used for the edc_consent process will also be used during data collection.', max_length=25, verbose_name='Language of consent'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='home_visit_permission',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, verbose_name='Has the participant given his/her permission for studystaff to make home visits for follow-up purposes (such as return of test results, contact about future studies or sharing BCPP results)?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_call_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Doesnt_work', "Doesn't work")], max_length=25, verbose_name='Has the participant given his/her permission for study staff to contact her at work for follow up purposes during the study?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectoffstudy',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreferral',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreferral',
            name='referral_code',
            field=models.CharField(choices=[('pending', '<data collection in progress>'), ('not_referred', 'Not referred'), ('TST-HIV', 'HIV test'), ('TST-IND', 'Indeterminate result'), ('MASA-CC', 'Known POS, MASA continued care'), ('MASA-DF', 'Known POS, MASA defaulter (was on ART)'), ('SMC-NEG', 'SMC (uncircumcised, hiv neg)'), ('SMC-UNK', 'SMC (uncircumcised, hiv result not known)'), ('UNK?-PR', 'HIV UNKNOWN, Pregnant'), ('NEG!-PR', 'NEG today, Pregnant'), ('POS!-PR', 'POS today, Pregnant'), ('POS#-AN', 'Known POS, Pregnant, on ART (ANC)'), ('POS#-PR', 'Known POS, Pregnant, not on ART'), ('POS!-HI', 'POS today, not on ART, high CD4)'), ('POS!-LO', 'POS today, not on ART, low CD4)'), ('POS#-HI', 'Known POS, not on ART, high CD4)'), ('POS#-LO', 'Known POS, not on ART, low CD4)'), ('POS!NVE', 'POS today, not on ART/NAIVE'), ('POS#NVE', 'Known POS, not on ART/NAIVE')], default='pending', editable=False, help_text='list of referral codes confirmed by the edc, comma delimited if more than one (derived).', max_length=50, verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason_missed',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name="If 'missed' above, Reason scheduled visit was missed"),
        ),
        migrations.AlterField(
            model_name='historicalsubstanceuse',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicaltbsymptoms',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalthirdpartner',
            name='first_haart',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Is this partner taking antiretroviral treatment?'),
        ),
        migrations.AlterField(
            model_name='historicalthirdpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='historicalthirdpartner',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalthirdpartner',
            name='partner_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Has your partner been tested for HIV in last 12 months'),
        ),
        migrations.AlterField(
            model_name='historicaltuberculosis',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicaluncircumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='historicaluncircumcised',
            name='future_circ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Would you ever consider being circumcised in the future?'),
        ),
        migrations.AlterField(
            model_name='historicaluncircumcised',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalviralloadresult',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivcareadherence',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivhealthcarecosts',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivlinkagetocare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivmedicalcare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivrelatedillness',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivresult',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivresultdocumentation',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='arvs_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Do you believe that treatment for HIV with antiretroviral therapy (or ARVs) can help HIV-positive people to live longer?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='hiv_pills',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Have you ever heard about treatment for HIV with pills called antiretroviral therapy or ARVs [or HAART]?'),
        ),
        migrations.AlterField(
            model_name='hivtested',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivtestinghistory',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivtestreview',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hivuntested',
            name='arvs_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, verbose_name='Do you believe that treatment for HIV with antiretroviral therapy (or ARVs) can help HIV-positive people to live longer?'),
        ),
        migrations.AlterField(
            model_name='hivuntested',
            name='hiv_pills',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, verbose_name='Have you ever heard about treatment for HIV with pills called antiretroviral therapy or ARVs or HAART?'),
        ),
        migrations.AlterField(
            model_name='hivuntested',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='householdcomposition',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='hypertensioncardiovascular',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='immigrationstatus',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='labourmarketwages',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='livewith',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='medicalcareaccess',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='medicaldiagnoses',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='medication',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='neighbourhoodproblems',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='nonpregnancy',
            name='hiv_last_pregnancy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], help_text='If respondent was aware that she was HIV-positive prior to last pregnancy', max_length=25, null=True, verbose_name='During your last pregnancy (not current pregnancy) were you tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='nonpregnancy',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='nonpregnancy',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AlterField(
            model_name='outpatientcare',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='participation',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='partnerresidency',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='pimacd4',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='pimavl',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='positiveparticipant',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='hiv_last_pregnancy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], help_text='If respondent was aware that she was HIV-positive prior to last pregnancy', max_length=25, null=True, verbose_name='During your last pregnancy (not current pregnancy) were you tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='recentpartner',
            name='first_haart',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Is this partner taking antiretroviral treatment?'),
        ),
        migrations.AlterField(
            model_name='recentpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='recentpartner',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='recentpartner',
            name='partner_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Has your partner been tested for HIV in last 12 months'),
        ),
        migrations.AlterField(
            model_name='reproductivehealth',
            name='currently_pregnant',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Are you currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='reproductivehealth',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='reproductivehealth',
            name='more_children',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=10, null=True, verbose_name='Do you wish to have a child now or in the future?'),
        ),
        migrations.AlterField(
            model_name='residencymobility',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='residencymobility',
            name='intend_residency',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Do you intend to move out of the community in the next 12 months?'),
        ),
        migrations.AlterField(
            model_name='residentmostlikely',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='resourceutilization',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='secondpartner',
            name='first_haart',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Is this partner taking antiretroviral treatment?'),
        ),
        migrations.AlterField(
            model_name='secondpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='secondpartner',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='secondpartner',
            name='partner_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Has your partner been tested for HIV in last 12 months'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='last_year_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></br>Leave blank if participant does not want to respond.</p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(([1-9])+|[1-9]{1}([0-9])+|0)$', 'Expected a number greater than or equal to zero')], verbose_name='In the past 12 months, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='sexualbehaviour',
            name='lifetime_sex_partners',
            field=models.CharField(blank=True, help_text="<p><i>Please remember to include casual and once-off partners</br>(prostitutes and truck drivers) as well as long-term partners</br>(spouses, boyfriends/girlfriends).<br>If you can't recall the exact number, please give a best guess.</i></p>", max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(([1-9])+|[1-9]{1}([0-9])+|0)$', 'Expected a number greater than or equal to zero')], verbose_name='In your lifetime, how many different people have you had sex with?'),
        ),
        migrations.AlterField(
            model_name='stigma',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='stigmaopinion',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='stiillnesses',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='language',
            field=models.CharField(choices=[('tn', 'Setswana'), ('en', 'English'), ('kck', 'Ikalanga'), ('hbs', 'Hambukushu')], help_text='The language used for the edc_consent process will also be used during data collection.', max_length=25, verbose_name='Language of consent'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='home_visit_permission',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, verbose_name='Has the participant given his/her permission for studystaff to make home visits for follow-up purposes (such as return of test results, contact about future studies or sharing BCPP results)?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_call_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Doesnt_work', "Doesn't work")], max_length=25, verbose_name='Has the participant given his/her permission for study staff to contact her at work for follow up purposes during the study?'),
        ),
        migrations.AlterField(
            model_name='subjectoffstudy',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectreferral',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectreferral',
            name='referral_code',
            field=models.CharField(choices=[('pending', '<data collection in progress>'), ('not_referred', 'Not referred'), ('TST-HIV', 'HIV test'), ('TST-IND', 'Indeterminate result'), ('MASA-CC', 'Known POS, MASA continued care'), ('MASA-DF', 'Known POS, MASA defaulter (was on ART)'), ('SMC-NEG', 'SMC (uncircumcised, hiv neg)'), ('SMC-UNK', 'SMC (uncircumcised, hiv result not known)'), ('UNK?-PR', 'HIV UNKNOWN, Pregnant'), ('NEG!-PR', 'NEG today, Pregnant'), ('POS!-PR', 'POS today, Pregnant'), ('POS#-AN', 'Known POS, Pregnant, on ART (ANC)'), ('POS#-PR', 'Known POS, Pregnant, not on ART'), ('POS!-HI', 'POS today, not on ART, high CD4)'), ('POS!-LO', 'POS today, not on ART, low CD4)'), ('POS#-HI', 'Known POS, not on ART, high CD4)'), ('POS#-LO', 'Known POS, not on ART, low CD4)'), ('POS!NVE', 'POS today, not on ART/NAIVE'), ('POS#NVE', 'Known POS, not on ART/NAIVE')], default='pending', editable=False, help_text='list of referral codes confirmed by the edc, comma delimited if more than one (derived).', max_length=50, verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason_missed',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name="If 'missed' above, Reason scheduled visit was missed"),
        ),
        migrations.AlterField(
            model_name='substanceuse',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='tbsymptoms',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='thirdpartner',
            name='first_haart',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Is this partner taking antiretroviral treatment?'),
        ),
        migrations.AlterField(
            model_name='thirdpartner',
            name='first_partner_cp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, null=True, verbose_name='To the best of your knowledge, did he/she ever have other sex partners while you two were having a sexual relationship?'),
        ),
        migrations.AlterField(
            model_name='thirdpartner',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='thirdpartner',
            name='partner_hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=25, verbose_name='Has your partner been tested for HIV in last 12 months'),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='uncircumcised',
            name='circumcised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure'), ('DWTA', "Don't want to answer")], max_length=15, null=True, verbose_name='Do you believe that male circumcision has any health benefits for you?'),
        ),
        migrations.AlterField(
            model_name='uncircumcised',
            name='future_circ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('not_sure', 'Not sure')], max_length=25, null=True, verbose_name='Would you ever consider being circumcised in the future?'),
        ),
        migrations.AlterField(
            model_name='uncircumcised',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='viralloadresult',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('subject_identifier', 'visit_schedule_name', 'schedule_name', 'visit_code', 'timepoint', 'visit_code_sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectrequisition',
            unique_together=set([('subject_visit', 'panel_name')]),
        ),
        migrations.AddField(
            model_name='ceaopd',
            name='subject_visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bcpp_subject.SubjectVisit'),
        ),
    ]
